# This workflow builds the typings and publishs a package to GitHub Packages when a release is created

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build-and-release-typings:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          # scope: '@octocat'
      - run: npm ci
      - run: rm -rf ./lib
      - run: npm run build:typings
      - run: npm publish --folder ./lib
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}